version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  app:
    build: .
    image: flask-example-01:latest
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=docker
    ports:
      - 8080:8080

volumes:
  dbdata: 